version: 2
updates:
  - commit-message:
      prefix: fix(actions)
    directory: /
    package-ecosystem: github-actions
    schedule:
      interval: monthly
    groups:
      actions-deps:
        patterns:
          - '*'
  - commit-message:
      prefix: fix(docker)
    directory: /
    package-ecosystem: docker
    schedule:
      interval: monthly
    groups:
      docker-deps:
        patterns:
          - '*'
